# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c911f07194f2d5a8ff43467783c4f81e1ffe937164fec72754f91efda029746d6f2e96ff72c7099c7871dbcda5c3485585e805a0f37c4940397970a0f9cbfb

test:
  secret_key_base: 340090b95eb91f6bbf9d5897720a69adf3a92d771bba27e8a930b54c023668802e832913f27d9dd0fef484c739430ac01d4e267f3e0dcf274a87a24d20966450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
